$define sharnir
>$undefine sharnir
DECLARE      > äéãÖÅÄçàÖ èãÄëíàçõ;
  LINE F1,F2,F3;  BANDY F4;  SF P;
OMEGA   W=(F1!F2) & F3 & F4;

$include:'str.rl'
PROGRAM  GAUSS(S1,FA);  TIME;  ATS;   ATS;
   NEW;  GAUSS(S1,FB);  TIME;  VAL;
  PR1; RESULT(R1,FU);
  PR1; RESULT(R1,FU);
  PR1; RESULT(R1,FU);
  PR1; RESULT(R1,FU);
  FA(U1)=(U1(I,4)+U1(I,6))*(U1(J,4)+U1(J,6));
  FB(U1)=U1(I)*U1(J);  FU(U)=U;
$include:'val.rl'
END